# Generated by Django 4.2.17 on 2025-01-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_mfa_enabled_customuser_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
